project:
  type: website
website:
  navbar:
    logo: CSAFE_Tools_handwriter.png
    search: true
    left:
      - text: Home
        file: index.qmd
    right:
      - icon: github
        href: https://github.com/CSAFE-ISU/handwriterApp
        aria-label: handwriterApp GitHub
format:
  html:
    css: csafe.css
    toc: true
    toc-depth: 2
    toc-location: left
